import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query';
import { BrowserRouter, Link, Route, Routes, useNavigate } from 'react-router-dom';
import { AppBar, Box, Button, Card, CardContent, Container, Grid, TextField, Toolbar, Typography } from '@mui/material';
import { LineChart, Line, PieChart, Pie, ResponsiveContainer, XAxis, YAxis, Tooltip } from 'recharts';
import { api } from './api/client';

const qc = new QueryClient();
function Shell({ children }) { return <><AppBar position="static"><Toolbar><Typography variant="h6" sx={{ flexGrow: 1 }}>SeniorConnect</Typography>{['/','/members','/events','/trips'].map((to)=><Button color="inherit" component={Link} to={to} key={to}>{to==='/'?'Dashboard':to.slice(1)}</Button>)}</Toolbar></AppBar><Container sx={{ py: 4 }}>{children}</Container></>; }
function Login() { const nav = useNavigate(); const [email,setEmail]=useState('admin@seniorconnect.local'); const [password,setPassword]=useState('Admin123!'); async function submit(e){e.preventDefault(); const {data}=await api.post('/auth/login',{email,password}); localStorage.setItem('token',data.access_token); nav('/');} return <Container maxWidth="sm"><Box component="form" onSubmit={submit} sx={{ mt: 10 }}><Typography variant="h4">Sign in</Typography><TextField fullWidth margin="normal" label="Email" value={email} onChange={e=>setEmail(e.target.value)}/><TextField fullWidth margin="normal" label="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><Button type="submit" variant="contained">Login</Button></Box></Container>; }
function Dashboard(){ const {data={}}=useQuery({queryKey:['dashboard'],queryFn:()=>api.get('/dashboard').then(r=>r.data)}); const cards=[['Total Members',data.total_members],['Active Members',data.active_members],['Expired Memberships',data.expired_memberships],['Renewals Due',data.renewals_due],['Upcoming Events',data.upcoming_events],['Event Registrations',data.event_registrations],['Attendance Rate',`${data.attendance_rate||0}%`],['Upcoming Trips',data.upcoming_trips],['Birthdays This Month',data.birthdays_this_month]]; const trend=[{m:'Jan',members:20,events:10},{m:'Feb',members:28,events:14},{m:'Mar',members:36,events:20},{m:'Apr',members:45,events:25}]; return <Shell><Typography variant="h4" gutterBottom>Community Dashboard</Typography><Grid container spacing={2}>{cards.map(([k,v])=><Grid item xs={12} sm={6} md={4} key={k}><Card><CardContent><Typography color="text.secondary">{k}</Typography><Typography variant="h4">{v ?? 0}</Typography></CardContent></Card></Grid>)}</Grid><Grid container spacing={2} sx={{mt:2}}><Grid item xs={12} md={8}><Card><CardContent><Typography>Membership Growth & Event Participation</Typography><ResponsiveContainer height={260}><LineChart data={trend}><XAxis dataKey="m"/><YAxis/><Tooltip/><Line dataKey="members"/><Line dataKey="events"/></LineChart></ResponsiveContainer></CardContent></Card></Grid><Grid item xs={12} md={4}><Card><CardContent><Typography>Age Distribution</Typography><ResponsiveContainer height={260}><PieChart><Pie data={[{name:'60-69',value:45},{name:'70-79',value:35},{name:'80+',value:20}]} dataKey="value" label /></PieChart></ResponsiveContainer></CardContent></Card></Grid></Grid><Box sx={{mt:3,display:'flex',gap:1,flexWrap:'wrap'}}>{['Add Member','Create Event','Create Trip','Send Notification','Renew Membership'].map(a=><Button variant="contained" key={a}>{a}</Button>)}</Box></Shell> }
function ListPage({title,path,fields}){ const {data=[]}=useQuery({queryKey:[path],queryFn:()=>api.get(path).then(r=>r.data)}); return <Shell><Typography variant="h4">{title}</Typography><Grid container spacing={2} sx={{mt:1}}>{data.map((item)=><Grid item xs={12} md={6} key={item.id}><Card><CardContent>{fields.map(f=><Typography key={f}>{f}: {String(item[f] ?? '')}</Typography>)}</CardContent></Card></Grid>)}</Grid></Shell>; }
function App(){return <QueryClientProvider client={qc}><BrowserRouter><Routes><Route path="/login" element={<Login/>}/><Route path="/" element={<Dashboard/>}/><Route path="/members" element={<ListPage title="Members" path="/members" fields={['member_id','first_name','last_name','mobile_number','email']}/>}/><Route path="/events" element={<ListPage title="Events" path="/events" fields={['name','venue','event_date','capacity']}/>}/><Route path="/trips" element={<ListPage title="Trips" path="/trips" fields={['name','destination','start_date','end_date','cost']}/>}/></Routes></BrowserRouter></QueryClientProvider>}
createRoot(document.getElementById('root')).render(<App/>);
