import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider, useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { Alert, AppBar, Box, Button, Card, CardContent, Container, CssBaseline, Dialog, DialogActions, DialogContent, DialogTitle, Grid, MenuItem, Paper, Stack, Table, TableBody, TableCell, TableHead, TableRow, TextField, Toolbar, Typography } from '@mui/material';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import { LineChart, Line, PieChart, Pie, ResponsiveContainer, XAxis, YAxis, Tooltip } from 'recharts';
import { api } from './api/client';

const qc = new QueryClient();
const theme = createTheme({ palette: { primary: { main: '#34568b' }, secondary: { main: '#f39c12' } }, typography: { fontSize: 16 } });
const navItems = [['/','Dashboard'],['/members','Members'],['/memberships','Memberships'],['/events','Events'],['/trips','Travel'],['/community','Community'],['/notifications','Notifications'],['/documents','Documents'],['/payments','Payments'],['/reports','Reports']];
const fieldLabel = (name) => name.replaceAll('_', ' ').replace(/\b\w/g, c => c.toUpperCase());
const toPayload = (form) => Object.fromEntries(Object.entries(form).filter(([, v]) => v !== ''));
function authed(){ return Boolean(localStorage.getItem('token')); }
function Protected({ children }) { return authed() ? children : <Navigate to="/login" replace />; }
function Shell({ children }) { const navigate = useNavigate(); return <><AppBar position="sticky"><Toolbar sx={{gap:1, flexWrap:'wrap'}}><Typography variant="h6" sx={{ mr: 2 }}>SeniorConnect</Typography>{navItems.map(([to,label])=><Button size="small" color="inherit" component={Link} to={to} key={to}>{label}</Button>)}<Box sx={{flexGrow:1}}/><Button color="inherit" onClick={()=>{localStorage.removeItem('token'); navigate('/login')}}>Logout</Button></Toolbar></AppBar><Container maxWidth="xl" sx={{ py: 4 }}>{children}</Container></>; }
function Login() { const nav = useNavigate(); const [form,setForm]=useState({email:'admin@seniorconnect.local',password:'Admin123!'}); const [error,setError]=useState(''); async function submit(e){e.preventDefault(); setError(''); try{ const {data}=await api.post('/auth/login',form); localStorage.setItem('token',data.access_token); nav('/'); } catch { setError('Invalid credentials'); }} return <Container maxWidth="sm"><Paper component="form" onSubmit={submit} sx={{ mt: 10, p: 4 }}><Typography variant="h4">SeniorConnect Sign In</Typography>{error && <Alert severity="error" sx={{my:2}}>{error}</Alert>}<TextField fullWidth margin="normal" label="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><TextField fullWidth margin="normal" label="Password" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><Button type="submit" variant="contained" size="large">Login</Button></Paper></Container>; }
function Dashboard(){ const nav=useNavigate(); const {data={}}=useQuery({queryKey:['dashboard'],queryFn:()=>api.get('/dashboard').then(r=>r.data)}); const cards=[['Total Members',data.total_members],['Active Members',data.active_members],['Expired Memberships',data.expired_memberships],['Renewals Due',data.renewals_due],['Upcoming Events',data.upcoming_events],['Event Registrations',data.event_registrations],['Attendance Rate',`${data.attendance_rate||0}%`],['Upcoming Trips',data.upcoming_trips],['Birthdays This Month',data.birthdays_this_month]]; const trend=[{m:'Jan',members:20,events:10,renewals:8},{m:'Feb',members:28,events:14,renewals:12},{m:'Mar',members:36,events:20,renewals:16},{m:'Apr',members:45,events:25,renewals:18}]; const actions=[['Add Member','/members'],['Create Event','/events'],['Create Trip','/trips'],['Send Notification','/notifications'],['Renew Membership','/memberships']]; return <Shell><Typography variant="h4" gutterBottom>Community Dashboard</Typography><Grid container spacing={2}>{cards.map(([k,v])=><Grid item xs={12} sm={6} md={4} key={k}><Card><CardContent><Typography color="text.secondary">{k}</Typography><Typography variant="h4">{v ?? 0}</Typography></CardContent></Card></Grid>)}</Grid><Grid container spacing={2} sx={{mt:2}}><Grid item xs={12} md={8}><Card><CardContent><Typography>Membership Growth, Event Participation, Renewals</Typography><ResponsiveContainer height={280}><LineChart data={trend}><XAxis dataKey="m"/><YAxis/><Tooltip/><Line dataKey="members"/><Line dataKey="events"/><Line dataKey="renewals"/></LineChart></ResponsiveContainer></CardContent></Card></Grid><Grid item xs={12} md={4}><Card><CardContent><Typography>Member Age Distribution</Typography><ResponsiveContainer height={280}><PieChart><Pie data={[{name:'60-69',value:45},{name:'70-79',value:35},{name:'80+',value:20}]} dataKey="value" label /></PieChart></ResponsiveContainer></CardContent></Card></Grid></Grid><Stack direction="row" spacing={1} sx={{mt:3, flexWrap:'wrap'}}>{actions.map(([a,to])=><Button variant="contained" key={a} onClick={()=>nav(to)}>{a}</Button>)}</Stack></Shell> }
function FormDialog({ title, fields, open, onClose, onSubmit }) { const [form,setForm]=useState({}); return <Dialog open={open} onClose={onClose} fullWidth maxWidth="md"><DialogTitle>{title}</DialogTitle><DialogContent><Grid container spacing={2} sx={{mt:0}}>{fields.map(f=><Grid item xs={12} md={f.full ? 12 : 6} key={f.name}><TextField select={Boolean(f.options)} multiline={f.multiline} rows={f.multiline?3:1} fullWidth type={f.type||'text'} label={f.label || fieldLabel(f.name)} InputLabelProps={f.type==='date'?{shrink:true}:undefined} value={form[f.name]||''} onChange={e=>setForm({...form,[f.name]:e.target.value})}>{f.options?.map(o=><MenuItem key={o} value={o}>{o}</MenuItem>)}</TextField></Grid>)}</Grid></DialogContent><DialogActions><Button onClick={onClose}>Cancel</Button><Button variant="contained" onClick={()=>onSubmit(toPayload(form))}>Save</Button></DialogActions></Dialog>; }
function DataPage({ title, path, columns, createFields, children }) { const client=useQueryClient(); const [open,setOpen]=useState(false); const [error,setError]=useState(''); const {data=[]}=useQuery({queryKey:[path],queryFn:()=>api.get(path).then(r=>r.data)}); const create=useMutation({mutationFn:(payload)=>api.post(path,payload), onSuccess:()=>{client.invalidateQueries({queryKey:[path]}); setOpen(false); setError('');}, onError:(e)=>setError(e.response?.data?.detail || 'Unable to save')}); return <Shell><Stack direction="row" justifyContent="space-between" alignItems="center"><Typography variant="h4">{title}</Typography>{createFields && <Button variant="contained" onClick={()=>setOpen(true)}>Add</Button>}</Stack>{error && <Alert severity="error" sx={{mt:2}}>{error}</Alert>}{children}<Paper sx={{mt:2, overflow:'auto'}}><Table><TableHead><TableRow>{columns.map(c=><TableCell key={c.key}>{c.label}</TableCell>)}</TableRow></TableHead><TableBody>{data.map(row=><TableRow key={row.id}>{columns.map(c=><TableCell key={c.key}>{c.render ? c.render(row) : String(row[c.key] ?? '')}</TableCell>)}</TableRow>)}</TableBody></Table></Paper>{createFields && <FormDialog title={`Add ${title}`} fields={createFields} open={open} onClose={()=>setOpen(false)} onSubmit={(p)=>create.mutate(p)} />}</Shell>; }
const memberFields=['first_name','last_name','mobile_number','email','date_of_birth','gender','blood_group','marital_status','address_line1','address_line2','city','state','country','postal_code','emergency_contact_name','emergency_relationship','emergency_phone','medical_conditions','allergies','medications','special_notes'].map(n=>({name:n,type:n.includes('date')?'date':'text',full:['medical_conditions','allergies','medications','special_notes'].includes(n),multiline:['medical_conditions','allergies','medications','special_notes'].includes(n)}));
function Members(){ return <DataPage title="Members" path="/members" columns={[{key:'member_id',label:'Member ID'},{key:'first_name',label:'First Name'},{key:'last_name',label:'Last Name'},{key:'mobile_number',label:'Mobile'},{key:'email',label:'Email'},{key:'city',label:'City'}]} createFields={memberFields}/>; }
function Memberships(){ return <DataPage title="Memberships" path="/memberships" columns={[{key:'membership_number',label:'Number'},{key:'member_id',label:'Member'},{key:'membership_type',label:'Type'},{key:'join_date',label:'Join'},{key:'expiry_date',label:'Expiry'},{key:'status',label:'Status'}]} createFields={[{name:'member_id'},{name:'membership_type',options:['Annual','Lifetime','Family','Premium']},{name:'join_date',type:'date'},{name:'expiry_date',type:'date'},{name:'status',options:['active','expired','suspended','pending_renewal']}]} />; }
function Events(){ const client=useQueryClient(); const [reg,setReg]=useState({event_id:'',member_id:''}); const [check,setCheck]=useState({registration_id:'',method:'manual'}); const register=useMutation({mutationFn:()=>api.post(`/events/${reg.event_id}/register/${reg.member_id}`), onSuccess:()=>client.invalidateQueries({queryKey:['/events']})}); const checkin=useMutation({mutationFn:()=>api.post(`/events/registrations/${check.registration_id}/check-in?method=${check.method}`)}); return <DataPage title="Events" path="/events" columns={[{key:'name',label:'Name'},{key:'venue',label:'Venue'},{key:'event_date',label:'Date'},{key:'capacity',label:'Capacity'}]} createFields={[{name:'name'},{name:'venue'},{name:'event_date',type:'date'},{name:'start_time'},{name:'end_time'},{name:'capacity'},{name:'registration_deadline',type:'date'},{name:'description',full:true,multiline:true}]}><ActionPanel title="Register Member / Check In"><TextField label="Event ID" value={reg.event_id} onChange={e=>setReg({...reg,event_id:e.target.value})}/><TextField label="Member ID" value={reg.member_id} onChange={e=>setReg({...reg,member_id:e.target.value})}/><Button variant="outlined" onClick={()=>register.mutate()}>Register</Button><TextField label="Registration ID" value={check.registration_id} onChange={e=>setCheck({...check,registration_id:e.target.value})}/><TextField label="Method" value={check.method} onChange={e=>setCheck({...check,method:e.target.value})}/><Button variant="outlined" onClick={()=>checkin.mutate()}>Check In</Button></ActionPanel></DataPage>; }
function Trips(){ const client=useQueryClient(); const [form,setForm]=useState({trip_id:'',member_id:''}); const reg=useMutation({mutationFn:()=>api.post(`/trips/${form.trip_id}/register/${form.member_id}`), onSuccess:()=>client.invalidateQueries({queryKey:['/trips']})}); return <DataPage title="Trips" path="/trips" columns={[{key:'name',label:'Name'},{key:'destination',label:'Destination'},{key:'start_date',label:'Start'},{key:'end_date',label:'End'},{key:'capacity',label:'Capacity'},{key:'cost',label:'Cost'}]} createFields={[{name:'name'},{name:'destination'},{name:'start_date',type:'date'},{name:'end_date',type:'date'},{name:'capacity'},{name:'cost'},{name:'organizer'},{name:'description',full:true,multiline:true}]}><ActionPanel title="Register Traveler"><TextField label="Trip ID" value={form.trip_id} onChange={e=>setForm({...form,trip_id:e.target.value})}/><TextField label="Member ID" value={form.member_id} onChange={e=>setForm({...form,member_id:e.target.value})}/><Button variant="outlined" onClick={()=>reg.mutate()}>Register</Button></ActionPanel></DataPage>; }
function ActionPanel({title, children}){ return <Card sx={{mt:2}}><CardContent><Typography variant="h6" gutterBottom>{title}</Typography><Stack direction="row" gap={1} flexWrap="wrap">{children}</Stack></CardContent></Card>; }
function Payments(){ return <DataPage title="Payments" path="/payments" columns={[{key:'receipt_number',label:'Receipt'},{key:'member_id',label:'Member'},{key:'payment_for',label:'For'},{key:'amount',label:'Amount'},{key:'payment_date',label:'Date'},{key:'payment_method',label:'Method'},{key:'status',label:'Status'}]} createFields={[{name:'member_id'},{name:'payment_for',options:['membership','event','travel']},{name:'amount'},{name:'payment_date',type:'date'},{name:'payment_method',options:['cash','card','upi','bank_transfer']},{name:'status',options:['paid','pending','failed']}]} />; }
function Notifications(){ return <DataPage title="Notifications" path="/notifications" columns={[{key:'type',label:'Type'},{key:'subject',label:'Subject'},{key:'channel',label:'Channel'},{key:'status',label:'Status'}]} createFields={[{name:'member_id'},{name:'type',options:['membership_renewal','event_reminder','trip_reminder','birthday','announcement']},{name:'subject'},{name:'body',full:true,multiline:true},{name:'channel',options:['email','sms_ready','whatsapp_ready']}]} />; }
function Community(){ return <Shell><Typography variant="h4">Community</Typography><Grid container spacing={2} sx={{mt:1}}><Grid item xs={12} md={6}><EmbeddedCrud title="Announcements" path="/announcements" columns={[{key:'title',label:'Title'},{key:'category',label:'Category'},{key:'body',label:'Message'}]} fields={[{name:'title'},{name:'category',options:['news','update','alert']},{name:'body',full:true,multiline:true}]}/></Grid><Grid item xs={12} md={6}><EmbeddedCrud title="Interest Groups" path="/groups" columns={[{key:'name',label:'Group'},{key:'description',label:'Description'}]} fields={[{name:'name'},{name:'description',full:true,multiline:true}]}/></Grid></Grid></Shell>; }
function EmbeddedCrud({title,path,columns,fields}){ const client=useQueryClient(); const [open,setOpen]=useState(false); const {data=[]}=useQuery({queryKey:[path],queryFn:()=>api.get(path).then(r=>r.data)}); const create=useMutation({mutationFn:(p)=>api.post(path,p), onSuccess:()=>{client.invalidateQueries({queryKey:[path]}); setOpen(false);}}); return <Card><CardContent><Stack direction="row" justifyContent="space-between"><Typography variant="h6">{title}</Typography><Button onClick={()=>setOpen(true)}>Add</Button></Stack><Table size="small"><TableBody>{data.map(r=><TableRow key={r.id}>{columns.map(c=><TableCell key={c.key}>{String(r[c.key]??'')}</TableCell>)}</TableRow>)}</TableBody></Table><FormDialog title={`Add ${title}`} fields={fields} open={open} onClose={()=>setOpen(false)} onSubmit={(p)=>create.mutate(p)}/></CardContent></Card>; }
function Documents(){ const client=useQueryClient(); const [meta,setMeta]=useState({member_id:'',document_type:'Aadhaar Copy'}); const [file,setFile]=useState(null); const upload=useMutation({mutationFn:()=>{const data=new FormData(); data.append('file',file); return api.post(`/documents/upload?member_id=${meta.member_id}&document_type=${encodeURIComponent(meta.document_type)}`, data);}, onSuccess:()=>client.invalidateQueries({queryKey:['/documents']})}); return <DataPage title="Documents" path="/documents" columns={[{key:'title',label:'Title'},{key:'document_type',label:'Type'},{key:'mime_type',label:'MIME'},{key:'size_bytes',label:'Size'},{key:'version',label:'Version'}]}><ActionPanel title="Upload Document"><TextField label="Member ID" value={meta.member_id} onChange={e=>setMeta({...meta,member_id:e.target.value})}/><TextField select label="Document Type" value={meta.document_type} onChange={e=>setMeta({...meta,document_type:e.target.value})}>{['Aadhaar Copy','Passport Copy','RTC Copy','Medical Documents','Membership Forms','Other Attachments'].map(o=><MenuItem key={o} value={o}>{o}</MenuItem>)}</TextField><Button component="label" variant="outlined">Choose File<input hidden type="file" onChange={e=>setFile(e.target.files?.[0])}/></Button><Typography>{file?.name}</Typography><Button variant="contained" disabled={!file || !meta.member_id} onClick={()=>upload.mutate()}>Upload</Button></ActionPanel></DataPage>; }
function Reports(){ const reports=['members','events','payments','trips']; return <Shell><Typography variant="h4">Reports & Analytics</Typography><Grid container spacing={2} sx={{mt:1}}>{reports.map(r=><Grid item xs={12} sm={6} md={3} key={r}><Card><CardContent><Typography variant="h6">{fieldLabel(r)} Report</Typography><Typography color="text.secondary" sx={{mb:2}}>Download current {r} data as CSV.</Typography><Button variant="contained" href={`/api/reports/${r}.csv`}>Download CSV</Button></CardContent></Card></Grid>)}</Grid></Shell>; }
function App(){ const routes = useMemo(() => [['/',<Dashboard/>],['/members',<Members/>],['/memberships',<Memberships/>],['/events',<Events/>],['/trips',<Trips/>],['/community',<Community/>],['/notifications',<Notifications/>],['/documents',<Documents/>],['/payments',<Payments/>],['/reports',<Reports/>]], []); return <ThemeProvider theme={theme}><CssBaseline/><QueryClientProvider client={qc}><BrowserRouter><Routes><Route path="/login" element={<Login/>}/>{routes.map(([path,el])=><Route key={path} path={path} element={<Protected>{el}</Protected>}/>)}</Routes></BrowserRouter></QueryClientProvider></ThemeProvider>; }
createRoot(document.getElementById('root')).render(<App/>);
